databases:
  - name: gotouchi_DB
    databaseName: gotouchi_db
    user: gotouchi
    region: singapore

services:
  - type: web
    name: gotouchi
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gotouchi_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

